apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleeper-players
  namespace: botsffl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleeper-players
  template:
    metadata:
      labels:
        app: sleeper-players
    spec:
      containers:
      - name: sleeper-players
        image: registry:5000/sleeper-players
        imagePullPolicy: Always
        env:
        - name: CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              key: CONSUMER_KEY
              name: ffl-twitter-account
        - name: CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              key: CONSUMER_SECRET
              name: ffl-twitter-account
        - name: KEY
          valueFrom:
            secretKeyRef:
              key: KEY
              name: ffl-twitter-account
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: SECRET
              name: ffl-twitter-account
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              key: REDIS_PASS
              name: redis-pass
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: REDIS_HOST
              name: redis-pass